### ISSUE TITLE
undefined: unix.SockaddrCAN

### ISSUE THREAD

**Issue by andrewarrow** [linklayer/go-socketcan#2]
When trying to compile on Darwin I get:
```
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface.go:55:3: undefined: unix.SIOCGIFINDEX
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface_isotp.go:35:25: undefined: unix.AF_CAN
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface_isotp.go:53:11: undefined: unix.SockaddrCAN
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface_isotp.go:78:11: undefined: unix.SockaddrCAN
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface_raw.go:14:25: undefined: unix.AF_CAN
/Users/aa/gp/src/github.com/linklayer/go-socketcan/pkg/socketcan/interface_raw.go:24:11: undefined: unix.SockaddrCAN
```

using the latest go from master:

go version devel +65f53da8e8 Wed Jun 12 14:58:18 2019 +0000 darwin/amd64

**Comment by ericevenchick** [comment]
Unfortunately, Darwin doesn't support SocketCAN, or the AF_CAN address family. This only works on Linux, sorry!

**Comment by andrewarrow** [comment]
hmm, I see. So if I wanted to read can data in isotp format from Mac, windows or linux I would need to write C code for each of them? (well, not linux, I can use go there)

**Comment by ericevenchick** [comment]
Yes, the kernel module that does ISOTP is Linux specific. This library also relies on the SocketCAN network stack, which is Linux specific. On Windows and Mac, you'll need some other way to access the CAN device.
